from sklearn.metrics import *
from sklearn.linear_model import LogisticRegression
import pandas as pd
mcc = make_scorer(matthews_corrcoef)
estimator = LogisticRegression(solver = "liblinear", C = 6, tol = 1, fit_intercept = True)

from genetic_selection import GeneticSelectionCV


from sklearn.model_selection import *
report = pd.DataFrame()
D = pd.read_csv('/content/sample_data/dis_sym_dataset_comb.csv')
X = D.iloc[:,1:]
y = D.iloc[:,0:1]
nofeats = [] 
chosen_feats = [] 
cvscore = [] 
rkf = RepeatedStratifiedKFold(n_repeats = 2, n_splits = 10)
selector = GeneticSelectionCV(estimator,
                              cv = rkf,
                              verbose = 0,
                              scoring = mcc,
                              max_features = 489,
                              n_population = 50,
                              crossover_proba = 0.5,
                              mutation_proba = 0.2,
                              n_generations = 10,
                              crossover_independent_proba=0.5,
                              mutation_independent_proba=0.05,
                              #tournament_size = 3,
                              n_gen_no_change=10,
                              caching=True,
                              n_jobs=-1)
selector = selector.fit(X, y)
genfeats = X.columns[selector.support_]
genfeats = list(genfeats)
print("Chosen Feats:  ", genfeats)

cv_score = selector.generation_scores_[-1]
nofeats.append(len(genfeats)) 
chosen_feats.append(genfeats) 
cvscore.append(cv_score)
report["No of Feats"] = nofeats
report["Chosen Feats"] = chosen_feats
report["Scores"] = cvscore
genfeats=['abdominal cramp',
 'abdominal distention',
 'abnormal behavior',
 'abnormal bleeding',
 'abnormal sensation',
 'abnormally frequent',
 'abscess',
 'aching',
 'acne',
 'acquiring drinking alcohol taking lot time',
 'affected part turning white',
 'anemia',
 'arm',
 'attack pain',
 'bacterial infection',
 'bad breath',
 'bad smelling thin vaginal discharge',
 'bad smelling vaginal discharge',
 'barky cough',
 'belching',
 'better sitting worse lying',
 'birth baby younger week gestational age',
 'bleeding gum',
 'bleeding skin',
 'blindness',
 'blindness one eye',
 'blister sunlight',
 'bloating',
 'blood stool',
 'blood urine',
 'bloody diarrhea',
 'blue',
 'bluish skin coloration',
 'blurred vision',
 'blurry vision',
 'body tremor',
 'bone pain',
 'bowed leg',
 'breathing problem',
 'bruising',
 'burning',
 'burning stabbing pain',
 'burning urination',
 'certain thought repeatedly',
 'change bowel movement',
 'change breast shape',
 'change color',
 'change hair',
 'change reflex',
 'change skin color red black',
 'change sleeping eating pattern',
 'change taste',
 'change voice',
 'characteristic facial feature',
 'characteristic rash',
 'chest discomfort',
 'chest pain',
 'chest tightness',
 'chill',
 'chronic cough',
 'chronic pain bladder',
 'clenched fist overlapping finger',
 'clumsy',
 'cm lump skin',
 'cold sweat',
 'coma',
 'confused thinking',
 'confusion',
 'constipation',
 'coolness',
 'coordination',
 'cough bloody mucus',
 'cough sputum production',
 'coughing',
 'coughing blood',
 'coughing including coughing blood',
 'coughing mucus',
 'crawl',
 'cry episode',
 'dark urine',
 'darker',
 'daytime sleepiness',
 'death child le one year age',
 'decreased ability feel pain',
 'decreased ability see',
 'decreased ability think',
 'decreased ability think remember',
 'decreased ability turn',
 'decreased appetite',
 'decreased motivation',
 'decreased range motion',
 'decreased taste',
 'decreased vision',
 'dehydration',
 'delayed physical growth',
 'delirium',
 'delusion',
 'dementia',
 'depending subtype abdominal pain',
 'depends organ involved',
 'depressed mood',
 'dermatitis herpetiformis',
 'developmental disability',
 'diarrhea',
 'diarrhea may bloody',
 'diarrhea mixed blood',
 'diarrhoea',
 'difficulty breathing',
 'difficulty cutting',
 'difficulty eating',
 'difficulty getting pregnant',
 'difficulty remembering recent event',
 'difficulty swallowing',
 'difficulty walking',
 'dimpling skin',
 'discharge penis',
 'disorientation',
 'distant object appear blurry',
 'distorted blurred vision distance',
 'dizziness',
 'double vision',
 'drinking large amount alcohol long period',
 'dry cough',
 'dry damp skin',
 'dry eye',
 'dry mouth',
 'ear pain',
 'easy prolonged bleeding',
 'emotional problem',
 'enlarged lymph node neck',
 'enlarged spleen',
 'enlarged thyroid',
 'enlargement thyroid',
 'enlargement tonsil',
 'episode severe',
 'erythema marginatum',
 'excess hair',
 'excessive amount uterine bleeding',
 'excessive daytime sleepiness',
 'excessive salivation',
 'expanding area redness site tick bite',
 'extreme sadness',
 'extremity weakness',
 'eye pain',
 'eye strain',
 'eyestrain',
 'fast heart rate',
 'fast heartbeat',
 'fatigue',
 'fear water',
 'feel need check thing repeatedly',
 'feeling cold',
 'feeling faint upon standing',
 'feeling generally unwell',
 'feeling like passing',
 'feeling need urinate right away',
 'feeling tired',
 'feeling tired time',
 'fever',
 'firm',
 'flat discolored spot bump may blister',
 'flu like illness',
 'flu like symptom',
 'fluid filled blister scab',
 'fluid nipple',
 'frequent infection',
 'frequent urination',
 'gas',
 'gradual loss coordination',
 'growth delay',
 'gum disease',
 'hair loss',
 'half ring finger',
 'hallucination usually hearing voice',
 'hard swelling skin',
 'hard time reading small print',
 'headache',
 'hearing loss',
 'hearing sound external sound present',
 'heartburn',
 'heat intolerance',
 'heavy period',
 'high blood pressure',
 'high body temperature',
 'hoarse voice',
 'hold reading material farther away',
 'inability child',
 'inability move feel one side body',
 'increased breath rate',
 'increased fat',
 'increased heart rate',
 'increased hunger',
 'increased risk broken bone',
 'increased risk infection',
 'increased thirst',
 'increasing weakening',
 'index',
 'infertility',
 'inflamed eye',
 'insomnia',
 'intellectual disability',
 'involuntary muscle movement',
 'involuntary sleep episode',
 'irregular edge',
 'irregular menstruation',
 'irritability',
 'irritation',
 'itchiness',
 'itching',
 'itching genital area',
 'itching result trouble sleeping',
 'itchy',
 'itchy blister',
 'itchy bump',
 'itchy ear',
 'jaundice',
 'jaw',
 'jerky body movement',
 'joint bone pain',
 'joint swelling',
 'large amount watery diarrhea',
 'large forehead',
 'large lymph node',
 'large lymph node around neck',
 'leg swelling',
 'light sensitivity',
 'little pain',
 'localized breast pain redness',
 'long term fatigue',
 'loose frequent bowel movement',
 'loose teeth',
 'loss appetite',
 'loss consciousness may sweating',
 'loss hair part head body',
 'loss lot blood childbirth',
 'loss smell',
 'loss vision one side',
 'low blood pressure',
 'low energy',
 'low red blood cell',
 'lower abdominal pain',
 'lump breast',
 'lump bump neck',
 'maculopapular rash',
 'malabsorption',
 'may symptom',
 'memory problem',
 'mental ability',
 'mental change',
 'mid dilated pupil',
 'middle finger',
 'mild moderate intellectual disability',
 'minimal',
 'missed period',
 'mole increasing size',
 'mood change',
 'mood swing',
 'mouth sore',
 'mouth ulcer',
 'multiple painful joint',
 'muscle ache difficulty breathing',
 'muscle cramp',
 'muscle joint pain',
 'muscle spasm',
 'muscle weakness',
 'muscle weakness beginning foot hand',
 'muscle weakness resulting inability move',
 'muscular pain',
 'myalgia',
 'nausea',
 'nausea vomiting',
 'nausea vomiting weight loss dehydration occur',
 'nearly undetectable spell',
 'neck',
 'neck stiffness',
 'needing urinate often',
 'newly inverted nipple',
 'non itchy skin ulcer',
 'non painful cyst middle eyelid',
 'nonaligned eye',
 'none non specific',
 'numbness',
 'object different size eye',
 'one eye myopia eye hyperopia',
 'opening upper lip may extend nose palate',
 'overlying redness',
 'pain area',
 'pain around ear',
 'pain doesnt go shingle',
 'pain sex',
 'pain specific bone',
 'painful',
 'painful blister lower leg',
 'painful heavy period',
 'painful joint base big toe',
 'painful rash occurring stripe',
 'painful skin',
 'painful swelling parotid gland',
 'painful swollen joint',
 'painful tender outer part elbow',
 'painless',
 'painless lump',
 'pale color',
 'pale skin',
 'pallor',
 'paralysis',
 'patch thick',
 'patch white skin',
 'perform certain routine repeatedly',
 'period vigorous shaking',
 'persistent rough white red patch mouth lasting longer week',
 'photophobia',
 'physical disability',
 'pimple like rash',
 'pinkish',
 'playing video game extremely long period time',
 'poor ability tolerate cold',
 'poor coordination',
 'poor tolerance heat',
 'post nasal drip',
 'problem language',
 'problem understanding speaking',
 'problem vision',
 'profuse sweating',
 'progressive muscle weakness',
 'prolonged',
 'prolonged cough',
 'prominent',
 'protein urine',
 'psychosis',
 'pulsing pain',
 'purple colored skin affected area',
 'purple colored skin lesion',
 'raised',
 'raised red blue lesion',
 'random outburst laughter',
 'rapid breathing',
 'recurring episode wheezing',
 'red',
 'red eye',
 'red purple darker skin',
 'red rash',
 'red scaly patch skin breast',
 'red skin',
 'red spot white eye',
 'red without blister',
 'reddish eye',
 'redness',
 'redness eye',
 'repetitive behavior',
 'restricted interest',
 'right lower abdominal pain',
 'rigidity',
 'ringing ear heartbeat',
 'rough skin growth',
 'runny nose',
 'scaly patch skin',
 'scratchiness',
 'seizure',
 'sensitivity smell',
 'sensitivity sound',
 'severe intellectual disability',
 'severe pain',
 'severe pain lower back abdomen',
 'shakiness',
 'shaking',
 'sharp chest pain',
 'shivering',
 'shock like pain one side face last second minute',
 'short height',
 'short stature',
 'shortness breath',
 'sit',
 'skin blister',
 'skin breakdown',
 'skin lesion generally pink color project outward',
 'skin peeling',
 'sleep problem',
 'sleeping problem',
 'small blister break open form painful ulcer',
 'small blister surrounding swelling',
 'small face',
 'small head',
 'small jaw',
 'sneezing',
 'social withdrawal',
 'sometimes symptom',
 'sore arm leg',
 'sore throat',
 'sore wrist',
 'stiff muscle',
 'stiff neck',
 'stiffness',
 'stomach pain',
 'stroke',
 'sudden',
 'sudden loss muscle strength',
 'sweat',
 'swell pain near tumor',
 'swelling',
 'swelling abdomen',
 'swelling hand foot',
 'swollen',
 'swollen hand foot',
 'swollen lymph node',
 'taste acid',
 'temporary fleeting vision one eye',
 'tender breast',
 'testicular pain',
 'tingling',
 'tingling hand foot',
 'tiredness',
 'tooth loss',
 'triangular tissue growth cornea',
 'trouble breathing nose',
 'trouble coordination',
 'trouble opening mouth',
 'trouble seeing',
 'trouble sensation',
 'trouble sleeping',
 'trouble social interaction',
 'trouble speaking',
 'trouble swallowing',
 'trouble talking',
 'trouble walking',
 'ulcer',
 'ulcer around genitals',
 'ulceration',
 'unable move',
 'unexplained weight loss',
 'unintended weight loss',
 'unpleasant smell present breath',
 'upper abdominal pain',
 'usage resulting problem',
 'vaginal bleeding',
 'vaginal bleeding without pain',
 'vaginal discharge',
 'variable',
 'vary depending part brain involved',
 'varying degree muscle weakness',
 'velvety skin',
 'vision loss',
 'vomiting',
 'warm',
 'watery eye',
 'weak grip',
 'weak muscle',
 'weakness limb',
 'weakness numbness affected leg',
 'webbed neck',
 'weight gain',
 'wet',
 'wheezing',
 'white patch vaginal discharge',
 'widespread pain',
 'withdrawal occurring stopping',
 'worrying',
 'yellow skin',
 'yellowish coloration skin white eye',
 'yellowish skin',
 'yellowish skin crust']

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
import numpy as np
import pandas as pd
from sklearn.metrics import *
from sklearn.linear_model import LogisticRegression
import pandas as pd
import pickle


data = pd.read_csv('C:/Users/Isha Patel/OneDrive/Desktop/PROJECTS/Evathon/dis_sym_dataset_comb.csv')
data1 = pd.read_csv('C:/Users/Isha Patel/OneDrive/Desktop/PROJECTS/Evathon/dis_sym_dataset_norm.csv')
y_new = data['label_dis']
X_new = data.iloc[:,1:]

for i in X_new.columns:
  if i not in genfeats:    
    X_new.drop(i, axis='columns', inplace=True)
    data1.drop(i, axis='columns', inplace=True)

X_train,X_test,y_train, y_test = train_test_split(X_new, y_new, test_size=0.2, random_state=42)
lr1=LogisticRegression(multi_class='multinomial', solver='lbfgs')
model = lr1.fit(X_train, y_train)

pickle.dump(model, open('model.pkl','wb'))